version: '3.7'
volumes:
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            device: /home/aybiouss/data/wordpress
            o: bind
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            device: /home/aybiouss/data/mariadb
            o: bind


services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        image: mariadb
        restart: always
        volumes:
            - mariadb_data:/var/lib/mysql 
        environment:
            - MYSQL_DATABASE=$(MYSQL_DATABASE)
            - MYSQL_USER=$(MYSQL_USER)
            - MYSQL_PASSWORD=$(MYSQL_PASSWORD)
            - MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD)
        networks:
            - net_work

    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        image: wordpress
        depends_on:
            - mariadb
        volumes:
            - wordpress_data:/var/www/wordpress
        restart: always
        links:
            - mariadb
        environment:
            - WORDPRESS_DB_HOST=$(WORDPRESS_DB_HOST)
            - WORDPRESS_DB_NAME=$(WORDPRESS_DB_NAME)
            - WORDPRESS_DB_USER=$(WORDPRESS_DB_USER)
            - WORDPRESS_DB_PASSWORD=$(WORDPRESS_DB_PASSWORD)
        networks:
            - net_work

    nginx:
        build: ./requirements/nginx
        container_name: nginx
        image: nginx
        ports:
            - "8085:80"
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/wordpress
        restart: always
        env_file:
            - .env
        networks:
            - net_work

networks:
    net_work:
