version: "3"
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=me
      - MYSQL_PASSWORD=12345
    volumes:
      - mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - wordpress
    init: true

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - wordpress
    depends_on:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=me
      - MYSQL_PASSWORD=12345
      - WORDPRESS_DB_HOST=mariadb  # Fix: Use the service name
      - WORDPRESS_DB_NAME=mariadb
      - WORDPRESS_DB_PASSWORD=12345
      - WORDPRESS_TABLE_PREFIX=
    ports:
      - 9000:9000
    restart: always
    init: true

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    networks:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    init: true

networks:
  wordpress:
    driver: bridge

volumes:
  mariadb:
  wordpress:
