version: '3.7'
volumes:
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            device: /home/aybiouss/data/wordpress
            o: bind
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            device: /home/aybiouss/data/mariadb
            o: bind


services:
    nginx:
        build: requirements/nginx
        container_name: nginx
        image: nginx
        ports:
            - 443:443
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/wordpress
        restart: on-failure
        env_file:
            - ../.env
        networks:
            - wordpress
        # init : true

    wordpress:
        build: requirements/wordpress
        container_name: wordpress
        image: wordpress
        depends_on:
            - mariadb
        volumes:
            - wordpress_data:/var/www/wordpress
        restart: on-failure
        env_file:
            - ../.env
        networks:
            - wordpress
        links:
            - mariadb
        ports:
            - 9000:9000
        # init : true

    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        image: mariadb
        restart: on-failure
        volumes:
            - mariadb_data:/var/lib/mysql 
        env_file:
            - ../.env
        networks:
            - wordpress
        # init : true

networks:
    wordpress:
        driver: bridge