version: '3.7'
services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        image: mariadb
        restart: always
        volumes:
            - mariadb:/var/lib/mysql 
        environment:
            - MYSQL_DATABASE=$(MYSQL_DATABASE)
            - MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD)
            - MYSQL_USER=$(MYSQL_USER)
            - MYSQL_PASSWORD=$(MYSQL_PASSWORD)
        networks:
            - wordpress
        # ports:
        #     - 3306:3306
        init : true

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/wordpress
        env_file:
            - .env
        networks:
            - wordpress
        restart: always
        init : true
        links:
            - mariadb
        environment:
            - MYSQL_DATABASE=$(MYSQL_DATABASE)
            - MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD)
            - MYSQL_USER=$(MYSQL_USER)
            - MYSQL_PASSWORD=$(MYSQL_PASSWORD)
            - WORDPRESS_DB_HOST=$(WORDPRESS_DB_HOST)
            - WORDPRESS_DB_NAME=$(WORDPRESS_DB_NAME)
            - WORDPRESS_DB_PASSWORD=$(WORDPRESS_DB_PASSWORD)
            - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX} #####
        # ports:
        #     - 9000:9000
        #     - 3306:3306

    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx
        # ports:
        #     - 443:443
        #     - 9000:9000
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/wordpress
        restart: always
        env_file:
            - .env
        networks:
            - wordpress
        init : true

networks:
    wordpress:
        driver: bridge

volumes :
    mariadb:
    wordpress:




    # volumes:
#     wordpress_data:
#         driver: local
#         driver_opts:
#             type: none
#             device: /home/aybiouss/data/wordpress
#             o: bind
#     mariadb_data:
#         driver: local
#         driver_opts:
#             type: none
#             device: /home/aybiouss/data/mariadb
#             o: bind
