volumes:
    wordpress_data:
        driver: local
        name: wordpress
        driver_opts:
            type: none
            device: /home/aybiouss/data/wordpress
            o: bind
    mariadb_data:
        driver: local
        name: mariadb
        driver_opts:
            type: none
            device: /home/aybiouss/data/mariadb
            o: bind


services:
    nginx:
        build: ./requirements/nginx
        pull_policy: never
        image: nginx
        container_name: nginx
        volumes:
        - wordpress_data:/var/www/wordpress
        restart: always
        ports:
          - "443:443"
        networks:
          - inception
        depends_on:
          - wordpress
        init : true

    wordpress:
        pull_policy: never
        image: wordpress
        container_name: wordpress
        volumes:
          - wordpress_data:/var/www/wordpress
        restart: always
        build: ./requirements/wordpress
        env_file:
          - .env
        networks:
          - inception
        depends_on:
          - mariadb
        init : true

    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        image: mariadb
        restart: on-failure
        volumes:
            - mariadb_data:/var/lib/mysql 
        env_file:
            - ./.env
        networks:
            - inception
        init : true

networks:
    inception:
        driver: bridge